### PR TITLE
Borer's Structuring Sense

### PR DESCRIPTION
**Pull request by adamliter**
@khanson679 The keywords and data validation rules still need to be updated, but I wanted you to take a look at this first. Thoughts or comments on anything?

### CODE REVIEW

**Comment by khanson679** [comment]
I didn't notice anything. Just need to confirm whether listed publisher locations vary so we know whether that can be separate.

**Comment by adamliter** [comment]
Yes, agreed. Just responded to you in the closed pull request thread about that.

Also, it might be worth raising the issue of books with multiple volumes in the `lx-unified-v2`. I think this is how the data should be stored (pending, as you say, a decision about how to handle publishers); however, the output of this entry with the current `biblatex-sp-unified` implementation might not be what it ultimately should be. You might want to try printing this in the test document and see what you think. I'll try to raise the issue over there sometime soon.

**Comment by khanson679** [comment]
Shall we pull it in then? It will be a while before we get a consensus from the working group. You go ahead and raise the issue with them.

Then I'll deal with testing and database rules.

**Comment by adamliter** [comment]
Sure, I'll merge it, and you can do the testing and the database rules, keeping in mind that we should still think about and research if this is how we really want to handle publishers. (And if it is, then we need to change the KoL entry.)

**Pull request merged**
