### PR TITLE
chomsky1986:knowledge

### PR DESCRIPTION
**Pull request by khanson679**
I think `@book` is good enough to merge. If you agree, then we'll open issues for the outstanding...issues.

### CODE REVIEW

**Comment by adamliter** [comment]
Sounds good.

**Comment by adamliter** [comment]
@khanson679 A bit belated, but should we be factoring out the publisher information into its own metadata file? The publisher and location should be pretty robustly consistent, I think.

**Comment by khanson679** [comment]
Not sure. The though crossed my mind, but I was under the impression that
the location is /not/ consistent. I know I've seen many books who list many
cities with the publisher, which implies that they have multiple locations.
But I have no real knowledge of how this works.

--Kenneth

**Comment by adamliter** [comment]
That's about right. There usually seems to be at least two cities given in most contemporary books, usually a city in the States and a city somewhere in Europe. I also honestly do not understand how this works, so maybe it's something we should try to research a little bit before making a decision. Perhaps there will also be some discussion of it with updating the Unified style guidelines that might be useful to us. But maybe if we take a look at other style guidelines or something?

Have you looked at CryptoBib yet, by the way? They do something that is sort of neat when it comes to publishers' locations. Granted, it looks like they're workflow is aimed at addressing when people want different styles of abbreviations for the locations, not necessarily for handling different locations. But it's something we could think about adapting if we do need to handle multiple locations or something.

**Comment by khanson679** [comment]
Yes, I think this will require a bit more work to figure out. No, haven't looked at CryptoBib yet.

**Comment by adamliter** [comment]
Yep, I raised this in https://github.com/lingbib/lingbib/issues/13. I'll try to look into it soon, but I might be largely busy until Monday. (Finally seem to be making a bit of progress on the thesis! :stuck_out_tongue_closed_eyes:)

**Pull request merged**
