### PR TITLE
casali1998:ATR

### PR DESCRIPTION
**Pull request by adamliter**
@khanson679 I'm guessing you'll want to do this slightly differently, perhaps with a `metadata_conferences.bib` file and a `metadata_proceedings.bib` file. What do you think?

### CODE REVIEW

**Comment by khanson679** [comment]
I mean, given how we've been doing things that's the only thing that makes any sense. I'm still not entirely sure about the naming scheme, because the entire database is metadata -- the things we're separating out are just bundles of shared/hierarchical data. But as the immediate next step I think that would be appropriate.

**Comment by khanson679** [comment]
I made the suggested change from Github, so I didn't regenerate `lingbib-master.bib`. We don't have a clear policy on that yet, but at the moment it probably isn't necessary since the result will be functionally identical.

**Comment by adamliter** [comment]
@khanson679 Fair enough. Let's not merge this just yet. There's one more thing I'm not entirely sure what we want to do about. I'll mention it in Ryver.

**Comment by khanson679** [comment]
Any updates on this one? I was wondering if maybe this problem will pop up elsewhere, when we have two "volume" levels in some hierarchy. I think this is logically distinct from what to do with multi-part proceedings specifically, so I'll open a separate issue (#12).

**Comment by adamliter** [comment]
I'm not sure I understand what you mean by "have two "volume" levels in some hierarchy". As far as I'm aware, there isn't anything like this.

But no, there isn't really an update on this. I think we should wait to do anything with publications in proceedings until we have a chance to discuss it in the `lx-unified-v2` working group. It will really depend if folks want to stick with what the Unified style guidelines currently say about proceedings or not.

**Pull request closed without merging**
