### PR TITLE
Adds requirements.txt for use w/pip & virtualenv

### PR DESCRIPTION
**Pull request by adamliter**

### CODE REVIEW

**Comment by khanson679** [comment]
Wouldn't it be more appropriate to include only our direct dependencies, eg PyYAML and Pybtex? I tested a `requirements.txt` with just Pybtex and it seemed to work as intended.

**Comment by khanson679** [comment]
Actually jsonschema might need to go in there too, since the lingbib-specific part of the schema will still live in lingbib/lingbib.

**Comment by adamliter** [comment]
I haven't thought about it that much or looked into it that much, but some people at least recommend including all dependencies, not just direct ones (see., e.g., [here](http://blog.miguelgrinberg.com/post/the-package-dependency-blues)).

Also, I added jsonschema. Let me know what you think.

**Comment by khanson679** [comment]
Okay, just add `click==5.1` (used in some scripts, and soon to be used in more) and we'll go with that.

**Comment by adamliter** [comment]
:+1:

**Comment by khanson679** [comment]
Okay. Just to be clear, there are still some variables outside of this list, including Python 2.7.x (and maybe libyaml). That's something else to document.

**Comment by khanson679** [comment]
Crap, we've already got a problem. That version of functools is not available for me, and I think shouldn't be in there at all. It's part of the standard library.

**Comment by adamliter** [comment]
That was the version that was installed for me when I ran `pip install jsonschema`. It should be available for you if you just do `pip install -r requirements.txt` (but you should set up a virtual environment to associate with wherever you have the repo cloned on your computer).

But we can also downgrade the functools thing. What's installed on your machine?

**Comment by khanson679** [comment]
I've got functools32==3.2.3-2. I don't even see your version on PyPI or Github.

**Comment by adamliter** [comment]
So it chokes if you do `pip install -r requirements.txt`?

**Comment by khanson679** [comment]
Yes.

**Comment by adamliter** [comment]
Huh, that's really odd. I just changed `requirements.txt` to:

```
click==5.1
functools32==3.2.3-2
jsonschema==2.5.1
latexcodec==1.0.2
pybtex==0.20.1
PyYAML==3.11
six==1.10.0
```

And then I did `pip uninstall functools32`, and then `pip install -r requirements.txt`, which produced:

```sh
Requirement already satisfied (use --upgrade to upgrade): click==5.1 in /Users/adamliter/.virtualenvs/lingbib/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting functools32==3.2.3-2 (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): jsonschema==2.5.1 in /Users/adamliter/.virtualenvs/lingbib/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): latexcodec==1.0.2 in /Users/adamliter/.virtualenvs/lingbib/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pybtex==0.20.1 in /Users/adamliter/.virtualenvs/lingbib/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in /Users/adamliter/.virtualenvs/lingbib/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /Users/adamliter/.virtualenvs/lingbib/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Installing collected packages: functools32
Successfully installed functools32-3.2.3.post2
```

And then `pip list` shows:

```
click (5.1)
functools32 (3.2.3.post2)
...
```

So even if it's installed as `functools32==3.2.3-2` it still installs as `functools32-3.2.3.post2` for me.

I'm confused. Ha. :confused:

**Comment by adamliter** [comment]
But we can just change it to `functools32==3.2.3-2` in the `requirements.txt` since that at least seems to work on both our machines.

**Comment by khanson679** [comment]
Can you give me your Python and PIP versions?

**Comment by adamliter** [comment]
Looks like this might be a problem with functools32? Dunno, but see here: https://github.com/MiCHiLU/python-functools32/issues/3

But I'm running Python 2.7.11 and pip 8.1.1.

**Comment by khanson679** [comment]
Maybe. I found the spec for version numbers, which suggest that it was only implemented in PIP v6. That could be the issue.

**Comment by adamliter** [comment]
Sounds good. Let me know what happens when you do that.

**Comment by khanson679** [comment]
Yep, upgrading PIP did the trick. Well, for now let's use the lowest common denominator, shall we?

**Comment by adamliter** [comment]
Meaning which one? :stuck_out_tongue: But sounds good to me.

**Comment by khanson679** [comment]
Meaning the one that works on old version.s

**Comment by adamliter** [comment]
Sounds good. Do you want to commit the change or shall I?

**Comment by khanson679** [comment]
I will.

**Comment by adamliter** [comment]
:+1:

**Pull request merged**
